# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G


# Base properties
    # minecraft version
    minecraft_version=1.20.1
    # forge version, latest version can be found on https://files.minecraftforge.net/
    forge_version=47.4.20
    mapping_channel=parchment
    mapping_version=2023.09.03

# Mod Properties
    mod_version=0.0.17
    maven_group=com.CuteNekoDragon.svo_core
    archives_base_name=svo_core
    mod_id=svo_core
    mod_name=Starlit Valley
    mod_url=
    mod_author=CuteNekoDragon
    mod_license=LGPLv3.0

# Dependencies
    gtceu_version=7.5.3
    ldlib_version=1.0.40.b
    registrate_version=MC1.20-1.3.11
    configuration_version=2.2.0
    jei_version=15.20.0.115
    emi_version = 1.1.22
    curios_version=5.14.1+1.20.1
    botania_version=1.20.1-454-FORGE
    ars_version=4.12.7.264
    guideme_version=20.1.15
    create_version = 6.0.8-289
    ponder_version = 1.0.91
    flywheel_version = 1.0.5
    geckolib_version=4.8.4
    resourcefulLibVersion=2.1.23
    resourcefulConfigVersion=2.1.2
    botariumVersion=2.3.3
    kubejs_version=2001.6.5-build.26