package com.CuteNekoDragon.Core.common.datagen;

import com.hollingsworth.arsnouveau.common.block.ModBlock;
import net.minecraft.world.item.Item;
import net.p3pp3rf1y.sophisticatedbackpacks.init.ModItems;
import net.p3pp3rf1y.sophisticatedstorage.init.ModBlocks;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;

public class GlobalDatagenArrays {

    public static List<Item> RemovedItems = new ArrayList<>(List.of(
            ModItems.STACK_UPGRADE_STARTER_TIER_TO_TIER_1_CONVERSION.get(),
            ModItems.STACK_UPGRADE_STARTER_TIER_TO_TIER_2_CONVERSION.get(),
            ModItems.STACK_UPGRADE_STARTER_TIER_TO_TIER_3_CONVERSION.get(),
            ModItems.STACK_UPGRADE_STARTER_TIER_TO_TIER_4_CONVERSION.get(),
            ModItems.STACK_UPGRADE_TIER_1_TO_TIER_2_CONVERSION.get(),
            ModItems.STACK_UPGRADE_TIER_1_TO_TIER_3_CONVERSION.get(),
            ModItems.STACK_UPGRADE_TIER_1_TO_TIER_4_CONVERSION.get(),
            ModItems.STACK_UPGRADE_TIER_2_TO_TIER_3_CONVERSION.get(),
            ModItems.STACK_UPGRADE_TIER_2_TO_TIER_4_CONVERSION.get(),
            ModItems.STACK_UPGRADE_TIER_3_TO_TIER_4_CONVERSION.get(),
            ModItems.NETHERITE_BACKPACK.get(),
            ModItems.FEEDING_UPGRADE.get(),
            ModItems.ADVANCED_FEEDING_UPGRADE.get(),
            ModItems.TOOL_SWAPPER_UPGRADE.get(),
            ModItems.ADVANCED_TOOL_SWAPPER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.FEEDING_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.ADVANCED_FEEDING_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_PLUS.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_TO_TIER_1_PLUS_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_TO_TIER_2_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_TO_TIER_3_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_TO_TIER_4_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_TO_TIER_5_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_PLUS_TO_TIER_2_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_PLUS_TO_TIER_3_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_PLUS_TO_TIER_4_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_1_PLUS_TO_TIER_5_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_2_TO_TIER_3_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_2_TO_TIER_4_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_2_TO_TIER_5_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_3_TO_TIER_4_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_3_TO_TIER_5_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.STACK_UPGRADE_TIER_4_TO_TIER_5_CONVERSION.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.BASIC_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.BASIC_TO_COPPER_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.BASIC_TO_IRON_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.BASIC_TO_GOLD_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.BASIC_TO_DIAMOND_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.BASIC_TO_NETHERITE_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.COPPER_TO_IRON_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.COPPER_TO_GOLD_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.COPPER_TO_DIAMOND_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.COPPER_TO_NETHERITE_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.IRON_TO_GOLD_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.IRON_TO_DIAMOND_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.IRON_TO_NETHERITE_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.GOLD_TO_DIAMOND_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.GOLD_TO_NETHERITE_TIER_UPGRADE.get(),
            net.p3pp3rf1y.sophisticatedstorage.init.ModItems.DIAMOND_TO_NETHERITE_TIER_UPGRADE.get(),
            ModBlocks.NETHERITE_BARREL_ITEM.get(),
            ModBlocks.LIMITED_BARREL_1_ITEM.get(),
            ModBlocks.LIMITED_BARREL_2_ITEM.get(),
            ModBlocks.LIMITED_BARREL_3_ITEM.get(),
            ModBlocks.LIMITED_BARREL_4_ITEM.get(),
            ModBlocks.LIMITED_COPPER_BARREL_1_ITEM.get(),
            ModBlocks.LIMITED_COPPER_BARREL_2_ITEM.get(),
            ModBlocks.LIMITED_COPPER_BARREL_3_ITEM.get(),
            ModBlocks.LIMITED_COPPER_BARREL_4_ITEM.get(),
            ModBlocks.LIMITED_IRON_BARREL_1_ITEM.get(),
            ModBlocks.LIMITED_IRON_BARREL_2_ITEM.get(),
            ModBlocks.LIMITED_IRON_BARREL_3_ITEM.get(),
            ModBlocks.LIMITED_IRON_BARREL_4_ITEM.get(),
            ModBlocks.LIMITED_GOLD_BARREL_1_ITEM.get(),
            ModBlocks.LIMITED_GOLD_BARREL_2_ITEM.get(),
            ModBlocks.LIMITED_GOLD_BARREL_3_ITEM.get(),
            ModBlocks.LIMITED_GOLD_BARREL_4_ITEM.get(),
            ModBlocks.LIMITED_DIAMOND_BARREL_1_ITEM.get(),
            ModBlocks.LIMITED_DIAMOND_BARREL_2_ITEM.get(),
            ModBlocks.LIMITED_DIAMOND_BARREL_3_ITEM.get(),
            ModBlocks.LIMITED_DIAMOND_BARREL_4_ITEM.get(),
            ModBlocks.LIMITED_NETHERITE_BARREL_1_ITEM.get(),
            ModBlocks.LIMITED_NETHERITE_BARREL_2_ITEM.get(),
            ModBlocks.LIMITED_NETHERITE_BARREL_3_ITEM.get(),
            ModBlocks.LIMITED_NETHERITE_BARREL_4_ITEM.get(),
            ModBlocks.NETHERITE_CHEST_ITEM.get(),
            ModBlocks.NETHERITE_SHULKER_BOX_ITEM.get()
    ));
}
